
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "x/dev", "main" ]
  pull_request:
    branches: [ "x/dev", "main" ]

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies and run tests
        run: |
          sudo apt-get update
          sudo apt-get -y install libportaudio2
          pip cache purge
          rm -rf .venv
          python -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install meson
          pip install ".[dev]"
          cd tests
          pytest -v *.py
